# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117b7678de1e744dd360800e777a0aec150a59b1236b9f8fa18fcff8f8745a3d0c821525874613703c857bb350f4c3c8d80dfae1e9f7bef73db2171876ff0366

test:
  secret_key_base: fcaf5345a605154b8061f5bd462bc5e8eaa9b72f9ea235026f20e67f31448d6abdb471a6febc7688628f223e784b43a08eaad03f9a08ccc4331c16c74e28e187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
